[2021-10-29 18:38:02,158] {processor.py:163} INFO - Started process (PID=17) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:02,160] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:38:02,161] {logging_mixin.py:109} INFO - [2021-10-29 18:38:02,161] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:02,184] {processor.py:632} INFO - DAG(s) dict_keys(['first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:02,330] {logging_mixin.py:109} INFO - [2021-10-29 18:38:02,329] {manager.py:496} INFO - Created Permission View: can read on DAG:first_dag
[2021-10-29 18:38:02,334] {logging_mixin.py:109} INFO - [2021-10-29 18:38:02,334] {manager.py:496} INFO - Created Permission View: can edit on DAG:first_dag
[2021-10-29 18:38:02,334] {logging_mixin.py:109} INFO - [2021-10-29 18:38:02,334] {dag.py:2389} INFO - Sync 1 DAGs
[2021-10-29 18:38:02,337] {logging_mixin.py:109} INFO - [2021-10-29 18:38:02,337] {dag.py:2408} INFO - Creating ORM DAG for first_dag
[2021-10-29 18:38:02,340] {logging_mixin.py:109} INFO - [2021-10-29 18:38:02,340] {dag.py:2914} INFO - Setting next_dagrun for first_dag to 2021-10-28T18:38:02.339893+00:00
[2021-10-29 18:38:02,346] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.189 seconds
[2021-10-29 18:38:32,444] {processor.py:163} INFO - Started process (PID=26) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:32,446] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:38:32,448] {logging_mixin.py:109} INFO - [2021-10-29 18:38:32,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:32,468] {processor.py:632} INFO - DAG(s) dict_keys(['first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:32,474] {logging_mixin.py:109} INFO - [2021-10-29 18:38:32,474] {dag.py:2389} INFO - Sync 1 DAGs
[2021-10-29 18:38:32,479] {logging_mixin.py:109} INFO - [2021-10-29 18:38:32,479] {dag.py:2914} INFO - Setting next_dagrun for first_dag to 2021-10-28T18:38:32.479445+00:00
[2021-10-29 18:38:32,485] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2021-10-29 18:38:39,698] {processor.py:163} INFO - Started process (PID=28) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:39,700] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:38:39,702] {logging_mixin.py:109} INFO - [2021-10-29 18:38:39,702] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:39,725] {logging_mixin.py:109} INFO - [2021-10-29 18:38:39,723] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 49, in <module>
    t1.doc_md = dedent(
NameError: name 'dedent' is not defined
[2021-10-29 18:38:39,731] {processor.py:668} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:39,732] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:39,768] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.073 seconds
[2021-10-29 18:38:48,783] {processor.py:163} INFO - Started process (PID=29) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:48,786] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:38:48,788] {logging_mixin.py:109} INFO - [2021-10-29 18:38:48,788] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:48,821] {logging_mixin.py:109} INFO - [2021-10-29 18:38:48,818] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36, in <module>
    t1.doc_md = dedent(
NameError: name 'dedent' is not defined
[2021-10-29 18:38:48,827] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:48,832] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.053 seconds
[2021-10-29 18:38:52,005] {processor.py:163} INFO - Started process (PID=30) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:52,008] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:38:52,010] {logging_mixin.py:109} INFO - [2021-10-29 18:38:52,010] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:52,041] {logging_mixin.py:109} INFO - [2021-10-29 18:38:52,040] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36, in <module>
    t1.doc_md = dedent(
NameError: name 'dedent' is not defined
[2021-10-29 18:38:52,047] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:38:52,053] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2021-10-29 18:39:22,288] {processor.py:163} INFO - Started process (PID=32) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:22,292] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:39:22,294] {logging_mixin.py:109} INFO - [2021-10-29 18:39:22,294] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:22,318] {logging_mixin.py:109} INFO - [2021-10-29 18:39:22,316] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36, in <module>
    t1.doc_md = dedent(
NameError: name 'dedent' is not defined
[2021-10-29 18:39:22,326] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:22,332] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2021-10-29 18:39:35,428] {processor.py:163} INFO - Started process (PID=33) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:35,432] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:39:35,434] {logging_mixin.py:109} INFO - [2021-10-29 18:39:35,434] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:35,465] {logging_mixin.py:109} INFO - [2021-10-29 18:39:35,463] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 39, in <module>
    bash_command=templated_command,
NameError: name 'templated_command' is not defined
[2021-10-29 18:39:35,471] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:35,476] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.053 seconds
[2021-10-29 18:39:37,698] {processor.py:163} INFO - Started process (PID=35) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:37,702] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:39:37,705] {logging_mixin.py:109} INFO - [2021-10-29 18:39:37,704] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:37,740] {logging_mixin.py:109} INFO - [2021-10-29 18:39:37,738] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 38, in <module>
    bash_command=templated_command,
NameError: name 'templated_command' is not defined
[2021-10-29 18:39:37,746] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:37,751] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.057 seconds
[2021-10-29 18:39:40,472] {processor.py:163} INFO - Started process (PID=36) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:40,474] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:39:40,476] {logging_mixin.py:109} INFO - [2021-10-29 18:39:40,476] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:40,507] {logging_mixin.py:109} INFO - [2021-10-29 18:39:40,505] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36, in <module>
    bash_command=templated_command,
NameError: name 'templated_command' is not defined
[2021-10-29 18:39:40,514] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:40,531] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.062 seconds
[2021-10-29 18:39:44,501] {processor.py:163} INFO - Started process (PID=37) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:44,505] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:39:44,508] {logging_mixin.py:109} INFO - [2021-10-29 18:39:44,508] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:44,544] {logging_mixin.py:109} INFO - [2021-10-29 18:39:44,542] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 33, in <module>
    t3 = BashOperator(
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['bash_command'] is required
[2021-10-29 18:39:44,551] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:39:44,558] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2021-10-29 18:40:00,679] {processor.py:163} INFO - Started process (PID=38) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:00,681] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:40:00,682] {logging_mixin.py:109} INFO - [2021-10-29 18:40:00,682] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:00,710] {logging_mixin.py:109} INFO - [2021-10-29 18:40:00,708] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 33, in <module>
    t3 = BashOperator(
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['bash_command'] is required
[2021-10-29 18:40:00,717] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:00,723] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.046 seconds
[2021-10-29 18:40:09,777] {processor.py:163} INFO - Started process (PID=40) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:09,780] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:40:09,782] {logging_mixin.py:109} INFO - [2021-10-29 18:40:09,782] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:09,813] {logging_mixin.py:109} INFO - [2021-10-29 18:40:09,811] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 32, in <module>
    t3 = BashOperator(
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['bash_command'] is required
[2021-10-29 18:40:09,819] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:09,824] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2021-10-29 18:40:32,534] {processor.py:163} INFO - Started process (PID=41) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:32,538] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:40:32,540] {logging_mixin.py:109} INFO - [2021-10-29 18:40:32,540] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:32,568] {logging_mixin.py:109} INFO - [2021-10-29 18:40:32,565] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 33, in <module>
    t3 = BashOperator(
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['bash_command'] is required
[2021-10-29 18:40:32,577] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:40:32,583] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2021-10-29 18:41:02,729] {processor.py:163} INFO - Started process (PID=43) to work on /opt/airflow/dags/first_dag.py
[2021-10-29 18:41:02,732] {processor.py:620} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2021-10-29 18:41:02,734] {logging_mixin.py:109} INFO - [2021-10-29 18:41:02,734] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2021-10-29 18:41:02,757] {logging_mixin.py:109} INFO - [2021-10-29 18:41:02,755] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 33, in <module>
    t3 = BashOperator(
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['bash_command'] is required
[2021-10-29 18:41:02,764] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2021-10-29 18:41:02,769] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
