[2021-10-30 06:50:08,176] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: first_python_dag.print_version manual__2021-10-30T06:50:05.995952+00:00 [queued]>
[2021-10-30 06:50:08,180] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: first_python_dag.print_version manual__2021-10-30T06:50:05.995952+00:00 [queued]>
[2021-10-30 06:50:08,182] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-30 06:50:08,182] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-30 06:50:08,183] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-30 06:50:08,189] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): print_version> on 2021-10-30 06:50:05.995952+00:00
[2021-10-30 06:50:08,191] {standard_task_runner.py:52} INFO - Started process 178 to run task
[2021-10-30 06:50:08,193] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'first_python_dag', 'print_version', 'manual__2021-10-30T06:50:05.995952+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/first_python_dag.py', '--cfg-path', '/tmp/tmpzfmppi12', '--error-file', '/tmp/tmpqafetnbj']
[2021-10-30 06:50:08,195] {standard_task_runner.py:77} INFO - Job 6: Subtask print_version
[2021-10-30 06:50:08,214] {logging_mixin.py:109} INFO - Running <TaskInstance: first_python_dag.print_version manual__2021-10-30T06:50:05.995952+00:00 [running]> on host a7208e2bdec4
[2021-10-30 06:50:08,228] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_python_dag
AIRFLOW_CTX_TASK_ID=print_version
AIRFLOW_CTX_EXECUTION_DATE=2021-10-30T06:50:05.995952+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-30T06:50:05.995952+00:00
[2021-10-30 06:50:08,230] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_version() missing 1 required positional argument: 'version'
[2021-10-30 06:50:08,234] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=first_python_dag, task_id=print_version, execution_date=20211030T065005, start_date=20211030T065008, end_date=20211030T065008
[2021-10-30 06:50:08,240] {standard_task_runner.py:88} ERROR - Failed to execute job 6 for task print_version
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.8/dist-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.8/dist-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.8/dist-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_version() missing 1 required positional argument: 'version'
[2021-10-30 06:50:08,247] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-30 06:50:08,254] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
